const Home = () => {
  return (
    <div>
      <Head>
        <title>Atomic - Time Tracking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
